using System;
using System.Text;
using System.Collections.Generic;

namespace drac {

    class WatVisitor {
        IDictionary<string, FunctionProperties> tableFunctions;
        HashSet<string> globalVars;
        HashSet<string> primiiveFunctions;
        int labelCounter = 0;

        public string GenerateLabel() {
            return $"${labelCounter++:00000}";
        }

        public WatVisitor(IDictionary<string, FunctionProperties> tableFunctions, HashSet<string> globalVars){
            this.tableFunctions = tableFunctions;
            this.globalVars = globalVars;

            primiiveFunctions.Add("printi");
            primiiveFunctions.Add("printc");
            primiiveFunctions.Add("prints");
            primiiveFunctions.Add("println");
            primiiveFunctions.Add("readi");
            primiiveFunctions.Add("reads");
            primiiveFunctions.Add("new");
            primiiveFunctions.Add("size");
            primiiveFunctions.Add("add");
            primiiveFunctions.Add("get");
            primiiveFunctions.Add("set");

        }

        public string Visit(DefList node){
            Console.WriteLine("Start DefList");
            return ";; WebAssembly text format code generated by "
                + "the drac compiler.\n\n"
                + "(module\n" 
                + "  (import \"drac\" \"printi\" (func $printi (param i32) (result i32)))\n"
                + "  (import \"drac\" \"printc\" (func $printc (param i32) (result i32)))\n"
                + "  (import \"drac\" \"prints\" (func $prints (param i32) (result i32)))\n"
                + "  (import \"drac\" \"println\" (func $println (result i32)))\n"
                + "  (import \"drac\" \"readi\" (func $readi (result i32)))\n"
                + "  (import \"drac\" \"reads\" (func $reads (result i32)))\n"
                + "  (import \"drac\" \"new\" (func $new (param i32) (result i32)))\n"
                + "  (import \"drac\" \"size\" (func $size (param i32) (result i32)))\n"
                + "  (import \"drac\" \"add\" (func $add (param i32 i32) (result i32)))\n"
                + "  (import \"drac\" \"get\" (func $get (param i32 i32) (result i32)))\n"
                + "  (import \"drac\" \"set\" (func $set (param i32 i32 i32) (result i32)))\n"
                + VisitChildren((dynamic) node)
                + ")\n";
        }

        public string visit(VarDef node){
            var sb = new StringBuilder();
            var globalVarName = node.AnchorToken.Lexeme;

            foreach (var identNode in node[0]){
                sb.Append($"(global  ${globalVarName} (mut i32) (i32.const 0))\n");
            }

            return sb.ToString();
        }

        public string Visit(FunDef node){
            var sb = new StringBuilder();

            if(node.AnchorToken.Lexeme == "main"){
                sb.Append($"  (func\n  (export \"main\")");
            }
            else{
                sb.Append($"  (func ${node.AnchorToken.Lexeme}");
            }

            sb.Append(Visit((dynamic) node[0])
            + "  (result i32)\n" 
            + "  (local $_temp i32)\n"
            +Visit((dynamic) node[1])
            +Visit((dynamic) node[2])
            + "  i32.const 0\n" 
            + "  return\n"
            + ")\n");
            
            return sb.ToString();
        }

        public string Visit(IdList node){
            //TODO
        }

        public string Visit(Identifier node){
            //TODO
        }

        public string Visit(VarDefList node){
            //TODO
        }

        public string Visit(StmtList node){
            //TODO
        }

        public string Visit(StmtIncr node){
            //TODO
        }

        public string Visit(StmtDecr node){
            //TODO
        }

        public string Visit(ExprList node){
            //TODO
        }

        public string Visit(StmtIf node){
            //TODO
        }

        public string Visit(ElseIfList node){
            //TODO
        }

        public string Visit(Elif node){
            //TODO
        }

        public string Visit(Else node){
            //TODO
        }

        public string Visit(StmtWhile node){
            var label1 = GenerateLabel();
            var label2 = GenerateLabel();

            return $"block  {label1}\n"
            + $"  loop  {label2}\n"
            + Visit((dynamic) node[0])
            + "  i32.eqz\n"
            + $"  br_if {label1}\n"
            + Visit((dynamic) node[1])
            + $"  br {label2}\n"
            + "  end\n"
            + "end\n";
        }

        public string Visit(StmtDoWhile node){
            var label1 = GenerateLabel();
            var label2 = GenerateLabel();

            return $"block  {label1}\n"
            + $"  loop  {label2}\n"
            + Visit((dynamic) node[0])
            + Visit((dynamic) node[1])
            + "  i32.eqz\n"
            + $"  br_if {label1}\n"
            + $"  br {label2}\n"
            + "  end\n"
            + "end\n";
        }

        public string Visit(Break node){
            //TODO
        }

        public string Visit(StmtReturn node){
            return Visit((dynamic) node) + " return\n"; 
        }

        public string Visit(Empty node){
            //TODO
        }

        public string Visit(ExprOr node){
            //TODO
        }

        public string Visit(ExprAnd node){
            //TODO
        }

        public string Visit(Compare node) {
            return VisitChildren(node) + "  i32.eq\n";
        }

        public string Visit(Different node) {
            return VisitChildren(node) + "  i32.ne\n";
        }

        public string Visit(LessThan node) {
            return VisitChildren(node) + "  i32.lt_s\n";
        }

        public string Visit(LessEqualThan node) {
            return VisitChildren(node) + "  i32.le_s\n";
        }

        public string Visit(MoreThan node) {
            return VisitChildren(node) + "  i32.gt_s\n";
        }

        public string Visit(MoreEqualThan node) {
            return VisitChildren(node) + "  i32.ge_s\n";
        }

        public string Visit(Plus node) {
            return VisitChildren(node) + "  i32.add\n";
        }

        public string Visit(Less node) {
            return VisitChildren(node) + "  i32.sub\n";
        }

        public string Visit(Multiply node) {
            return VisitChildren(node) + "  i32.mul\n";
        }

        public string Visit(Division node) {
            return VisitChildren(node) + "  i32.div_s\n";
        }

        public string Visit(Module node) {
            return VisitChildren(node) + "  i32.rem_s\n";
        }

        public string Visit(ExprUnary node){
            //TODO
        }

        public string Visit(Not node) {
            return "    i32.const 0\n"
                    + Visit((dynamic) node[0])
                    + "    i32.sub\n";
        }

        public string Visit(True node) {
            return "  i32.const 1\n";
        }
    
        public string Visit(False node) {
            return "  i32.const 0\n";
        }

        public string Visit (IntLiteral node) {
            var result = node.AnchorToken.Lexeme;
            return $"  i32.const {result}\n";
        }

        public string Visit(CharLit node){
            var result = char.ConvertToUtf32(node.AnchorToken.Lexeme, 0);
            return $"  i32.const {result}\n";
        }

        public string Visit(StringLit node){
            var sb = new StringBuilder();
            var lstString = AsCodePoints(node.AnchorToken.Lexeme);
            sb.Append("  i.32.const 0\n"
                    + "  call $new\n"
                    + "  local.set $_temp\n"
                    + "  local.get $_temp\n");
            foreach(var c in lstString) {
                sb.Append("  local.get $_temp\n");
            }
            foreach(var c in lstString){
                sb.Append($"  i32.const {c}\n"
                         + "  call $add\n"
                         + "  drop\n"
                         + "  \n");
            }
            return sb.ToString();
        }

        public string Visit(Assign node){
            //TODO
        }

        public string Visit(FunCall node){
            //TODO
        }

        public string Visit(ParametersList node){
            //TODO
        }

        public string Visit(IntLiteral node){
            return $"  i32.const {node.AnchorToken.Lexeme}\n";
        }

        public string VisitChildren(Node node){
            var sb = new StringBuilder();
            foreach (var n in node) {
                sb.Append(Visit((dynamic) n));
            }
            return sb.ToString();
		}

        public static IList<int> AsCodePoints(String str) {
            var result = new List<int>(str.Length);

            for (var i = 0; i < str.Length; i++) {
                result.Add(char.ConvertToUtf32(str, i));
                
                if (char.IsHighSurrogate(str, i)) {
                    i++;
                }
            }
            return result;
        }
    }
}